name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [ 'x86', 'x64', 'ARM64' ]
    name: Build ${{ matrix.platform }}
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
          cache: true
          cache-dependency-path: |
            **/packages.lock.json
      - name: Restore dependencies
        run: dotnet restore --locked-mode
      - name: Build
        run: dotnet build --no-restore -c Release -p:Platform=${{ matrix.platform }}
      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
