name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [ 'x86', 'x64', 'ARM64' ]
    name: Build ${{ matrix.platform }}
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
          cache: true
          cache-dependency-path: |
            **/packages.lock.json
      - name: Restore dependencies
        run: dotnet restore --locked-mode
      - name: Build
        run: dotnet build --no-restore -c Release -p:Platform=${{ matrix.platform }}
      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish --no-build -c Release -p:Platform=${{ matrix.platform }} -p:PublishDir=${{ github.workspace }}/publish
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: ${{ matrix.platform }}
          path: ${{ github.workspace }}/publish
